# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('mobile_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
