# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Тип порушення')),
                ('enabled', models.BooleanField(db_index=True, default=False, verbose_name='Увімкнено')),
            ],
            options={
                'verbose_name_plural': 'Типи порушень',
                'verbose_name': 'Тип порушення',
            },
        ),
    ]
