# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 19:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160527_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enqueued', 'Enqueued'), ('accepted', 'Accepted by police'), ('in_progress', 'In progress'), ('complete', 'Complete'), ('invalid', 'Invalid'), ('canceled', 'Canceled')], max_length=255)),
                ('description', models.TextField(blank=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='claim',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 7, 22, 33, 6, 809166)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimstate',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='core.Claim'),
        ),
    ]
