# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160607_2233'),
    ]

    operations = [
        migrations.DeleteModel(name='claim'),
        migrations.DeleteModel(name='claimstate')
    ]
