# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_claim_claimstate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at'], 'permissions': (('can_list_all_claims', 'Can list all claims'),), 'verbose_name': 'Скарга', 'verbose_name_plural': 'Скарги'},
        ),
        migrations.AlterField(
            model_name='claim',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='city',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Місто'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='license_plates',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Номери автомобілів'),
        ),
    ]
