# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 17:35
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20160715_2035'),
        ('core', '0008_auto_20160627_0003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claim',
            options={'ordering': ['-created_at'], 'permissions': (('can_list_all_claims', 'Can list all claims'),)},
        ),
        migrations.AlterModelOptions(
            name='crimetype',
            options={},
        ),
        migrations.RemoveField(
            model_name='claim',
            name='images',
        ),
        migrations.AddField(
            model_name='claim',
            name='media',
            field=models.ManyToManyField(blank=True, to='media.MediaFileModel'),
        ),
        migrations.AddField(
            model_name='claim',
            name='media_filenames',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=None),
        ),
        migrations.AlterField(
            model_name='claim',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='claim',
            name='city',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='claim',
            name='crimetypes',
            field=models.ManyToManyField(to='core.CrimeType'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='claim',
            name='license_plates',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('complete', 'Complete'), ('enqueued', 'Enqueued'), ('accepted', 'Accepted by police'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('invalid', 'Invalid'), ('canceled', 'Canceled')], db_index=True, default='received', max_length=255),
        ),
        migrations.AlterField(
            model_name='claim',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claimstate',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('complete', 'Complete'), ('enqueued', 'Enqueued'), ('accepted', 'Accepted by police'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('invalid', 'Invalid'), ('canceled', 'Canceled')], max_length=255),
        ),
        migrations.AlterField(
            model_name='crimetype',
            name='enabled',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='crimetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
