# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160715_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='claim',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
