# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-15 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import media.models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediafilemodel',
            options={},
        ),
        migrations.AddField(
            model_name='mediafilemodel',
            name='original_filename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='mediafilemodel',
            name='file',
            field=models.ImageField(upload_to=media.models.generate_upload_path),
        ),
    ]
